{
 "title": "Energie",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "collector_name",
    "label": "Collector Name",
    "query": {
     "query": "label_values(estimenergy_day_kwh, name)"
    }
   },
   {
    "name": "power_entity",
    "label": "Power Entity",
    "query": {
     "query": "label_values(homeassistant_sensor_power_w, entity)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Leistung",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_power_w{entity=\"$power_entity\"}",
     "legendFormat": "Leistung"
    }
   ]
  },
  {
   "title": "Leistung",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_power_w{entity=\"sensor.house_power_consumption\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Energieverbrauch insgesamt",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "estimenergy_total_kwh{name=\"$collector_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Verbrauch",
   "type": "stat",
   "gridPos": { "h": 18, "w": 2, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "estimenergy_day_kwh{name=\"$collector_name\"}",
     "legendFormat": "Tag"
    },
    {
     "expr": "estimenergy_month_kwh_predicted{name=\"$collector_name\"}",
     "legendFormat": "Monat"
    },
    {
     "expr": "estimenergy_year_kwh_predicted{name=\"$collector_name\"}",
     "legendFormat": "Jahr"
    }
   ]
  },
  {
   "title": "Kosten",
   "type": "stat",
   "gridPos": { "h": 18, "w": 2, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "estimenergy_day_cost{name=\"$collector_name\"}",
     "legendFormat": "Tag"
    },
    {
     "expr": "estimenergy_month_cost_predicted{name=\"$collector_name\"}",
     "legendFormat": "Monat"
    },
    {
     "expr": "estimenergy_year_cost_predicted{name=\"$collector_name\"}",
     "legendFormat": "Jahr"
    }
   ]
  },
  {
   "title": "Kostendifferenz",
   "type": "stat",
   "gridPos": { "h": 18, "w": 2, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "estimenergy_day_cost_difference{name=\"$collector_name\"}",
     "legendFormat": "Tag"
    },
    {
     "expr": "estimenergy_month_cost_difference_predicted{name=\"$collector_name\"}",
     "legendFormat": "Monat"
    },
    {
     "expr": "estimenergy_year_cost_difference_predicted{name=\"$collector_name\"}",
     "legendFormat": "Jahr"
    }
   ]
  },
  {
   "title": "Genauigkeit",
   "type": "stat",
   "gridPos": { "h": 18, "w": 2, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "estimenergy_day_accuracy{name=\"$collector_name\"}",
     "legendFormat": "Tag"
    },
    {
     "expr": "estimenergy_month_accuracy{name=\"$collector_name\"}",
     "legendFormat": "Monat"
    },
    {
     "expr": "estimenergy_year_accuracy{name=\"$collector_name\"}",
     "legendFormat": "Jahr"
    }
   ]
  },
  {
   "title": "Energie",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "estimenergy_day_kwh{name=\"$collector_name\"}",
     "legendFormat": "Energieverbrauch"
    },
    {
     "expr": "estimenergy_day_cost{name=\"$collector_name\"}",
     "legendFormat": "Energiekosten"
    }
   ]
  }
 ]
}