services:
  estimenergy:
    # change this part to image: ghcr.io/eulemitkeule/estimenergy:<version>
    build:
      context: .
      dockerfile: Dockerfile
    container_name: estimenergy
    restart: unless-stopped
    networks:
      - estimenergy
    ports:
      - 12321:12321
    # change this part to /path/to/config.yml:/config/config.yml
    volumes:
      - ./config.yml:/config/config.yml

  estimenergy-postgres:
    image: postgres:15.2-alpine
    container_name: estimenergy-postgres
    restart: unless-stopped
    networks:
      - estimenergy
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_INITDB_ARGS=--encoding=UTF8

  estimenergy-influxdb:
    image: influxdb:2.7.0-alpine
    container_name: estimenergy-influxdb
    restart: unless-stopped
    networks:
      - estimenergy
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
      - DOCKER_INFLUXDB_REPORTING_DISABLED=true
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_HTTP_AUTH_ENABLED=true

networks:
  estimenergy:
    driver: bridge
    name: estimenergy
