name: Code Quality

on:
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]
  workflow_dispatch:

env:
  SONAR_PROJECT_KEY: EuleMitKeule_EstimEnergy
  SONAR_PROJECT_NAME: EstimEnergy
  SONAR_PROJECT_ORGANIZATION: eule

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2

      - name: Install dependencies
        run: |
          poetry install --with dev

      - name: Run black
        run: |
          poetry run black --check estimenergy tests custom_components/estimenergy_integration --diff

  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2

      - name: Install dependencies
        run: |
          poetry install --with dev

      - name: Run isort
        run: |
          poetry run isort --check-only --diff estimenergy tests custom_components/estimenergy_integration

  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2

      - name: Install dependencies
        run: |
          poetry install --with dev

      - name: Run mypy
        run: |
          poetry run mypy estimenergy tests custom_components/estimenergy_integration

  bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2

      - name: Install dependencies
        run: |
          poetry install --with dev

      - name: Run bandit
        run: |
          poetry run bandit -r estimenergy custom_components/estimenergy_integration

  hassfest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2

      - name: Install dependencies
        run: |
          poetry install --with dev

      - name: Run hassfest
        uses: home-assistant/actions/hassfest@master

  hacs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2

      - name: Install dependencies
        run: |
          poetry install --with dev

      - name: Run hacs
        uses: hacs/action@main
        with:
          category: integration

  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2

      - name: Install dependencies
        run: |
          poetry install --with dev

      - name: Run pytest
        run: |
          poetry run pytest --cov=estimenergy --cov-report=xml

      - name: Run SonarCloud analysis
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=${{ env.SONAR_PROJECT_ORGANIZATION }}
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.sources=estimenergy,custom_components/estimenergy_integration
            -Dsonar.tests=tests/
            -Dsonar.python.version=3.9
